import os

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
GIPHY_API_KEY = os.getenv("GIPHY_API_KEY")
DATABASE_URL = os.environ["DATABASE_URL"]